version: '3'
services:

  backend:
    image: api
    build: ../backend/
    ports:
      - "8000:8000"

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    env_file:
      - influxdb.env
    volumes:
      - type: bind
        source: ./influxdb
        target: /var/lib/influxdb2

  node-red:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - type: bind
        source: ./node-red
        target: /data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - type: bind
        source: "./mosquitto/config/"
        target: "/mosquitto/config/"
      - type: bind
        source: "./mosquitto/data/"
        target: "/mosquitto/data/"
      - type: bind
        source: "./mosquitto/log/"
        target: "/mosquitto/log/"
      - type: bind
        source: "./mosquitto/security/"
        target: "/mosquitto/security/"
