version: '3'
services:
  influxdb:
    image: influxdb 
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=sweetsignal 
      - DOCKER_INFLUXDB_INIT_PASSWORD=sweetsignal12345 
      - DOCKER_INFLUXDB_INIT_ORG=sweetsignal 
      - DOCKER_INFLUXDB_INIT_BUCKET=IOT-buck
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=c7sFQXMCgt6WShaWHuJkcHDpnFJhdaTcb8xtveNPoFFixtj2_-yMpUqc5HvmJpADU2sSEmlMXY_oXfc4slJcXQ==
    volumes:
      - type: bind
        source: ./influxdb
        target: /var/lib/influxdb2

  node-red:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - type: bind
        source: ./node-red
        target: /data
  nginx:
    image: nginx
    ports:
      - "8080:80"
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - type: bind
        source: "./mosquitto/config/"
        target: "/mosquitto/config/"
      - type: bind
        source: "./mosquitto/data/"
        target: "/mosquitto/data/"     
      - type: bind
        source: "./mosquitto/log/"
        target: "/mosquitto/log/"
      - type: bind
        source: "./mosquitto/security/"
        target: "/mosquitto/security/"



  